kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
  - role: worker
  - role: worker
  - role: worker

  #Usage kind create cluster --name devops-project --config kind-config.yaml
  #kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.2/cert-manager.crds.yaml
  #kubectl create namespace security   # matches your Terraform namespace
  #helm repo add jetstack https://charts.jetstack.io
  #helm repo update
  #helm install cert-manager jetstack/cert-manager --namespace security --set installCRDs=true


